### PR TITLE
Full rework of rows and records parsing

### LINKED ISSUE #6: Record field names surrounded with quotes not valid
image

### LINKED ISSUE #22: No rows syntax support
Row types don't parse.

A potential implementation should also unify row types and record syntax under the same machinery.

### PR DESCRIPTION
**Pull request by postsolar**
Closes #6 
Closes #22 

~~Quoted field names parse correctly both at the value level and the type level.
But it only deals with *record* fields. From what I gather there's no notion of *row* fields yet in the parser.~~

I turned it into a full rewrite of rows and records parsing. I think I covered all possible variants of syntax. See updated tests.
I also lifted the wildcard `_` into being an operator in the highlight queries and removed `()`-unit constructor because it conflicts with empty rows (aside from not being a thing in PS).

### CODE REVIEW

**Review by Maskhjarna — CHANGES_REQUESTED** [review]
This PR seems to break on constructors among function parameters, like:

```purescript
module Test where

type A = { a :: Int }

f2 :: A -> Int
f2 { a } = a
```
producing

```tree-sitter
(purescript [0, 0] - [6, 0]
  name: (qualified_module [0, 7] - [0, 11]
    (module [0, 7] - [0, 11]))
  (where [0, 12] - [0, 17])
  (ERROR [2, 0] - [5, 12]
    (type_alias [2, 0] - [2, 21]
      name: (type [2, 5] - [2, 6])
      (record_type_literal [2, 9] - [2, 21]
        (row_field [2, 11] - [2, 19]
          (field_name [2, 11] - [2, 12])
          (type_name [2, 16] - [2, 19]
            (type [2, 16] - [2, 19])))))
    (signature [4, 0] - [4, 14]
      name: (variable [4, 0] - [4, 2])
      type: (fun [4, 6] - [4, 14]
        (type_name [4, 6] - [4, 7]
          (type [4, 6] - [4, 7]))
        (type_name [4, 11] - [4, 14]
          (type [4, 11] - [4, 14]))))
    (variable [5, 0] - [5, 2])
    (field_name [5, 5] - [5, 6])
    (ERROR [5, 7] - [5, 8])
    (exp_name [5, 11] - [5, 12]
      (variable [5, 11] - [5, 12]))))
```

**Comment by postsolar** [comment]
Nice catch, I'll look into this.

In the meanwhile I was also working on some other things (holes, wildcards, less Haskell, and I think it might require a big rewrite of `exp.js` for infix expression sections to parse correctly) in this same branch because I depend on the `$.wildcard`, but I will wait until this one is merged because these new changes will likely grow too big due to how much of Haskell stuff has to be reworked.

While I was working on these further changes I also noticed I somehow forgot that not only variables can be placed in `{ ... | r }`, so I left out syntax like `{ ... | A }` :rofl:

**Comment by postsolar** [comment]
I think it's ready now 👍.

**Review by Maskhjarna — CHANGES_REQUESTED** [review]
Great work, although it seems like record construction among function parameters is broken.

```purescript
module Test where

type A = { a :: Int }

f :: A -> Int
f { a } = a

g :: Int
g = f { a: 5 }
```
gives

```
(purescript [0, 0] - [10, 0]
  name: (qualified_module [0, 7] - [0, 11]
    (module [0, 7] - [0, 11]))
  (where [0, 12] - [0, 17])
  (type_alias [2, 0] - [2, 21]
    name: (type [2, 5] - [2, 6])
    (record_type_literal [2, 9] - [2, 21]
      (row_field [2, 11] - [2, 19]
        (field_name [2, 11] - [2, 12])
        (type_name [2, 16] - [2, 19]
          (type [2, 16] - [2, 19])))))
  (signature [4, 0] - [4, 13]
    name: (variable [4, 0] - [4, 1])
    type: (fun [4, 5] - [4, 13]
      (type_name [4, 5] - [4, 6]
        (type [4, 5] - [4, 6]))
      (type_name [4, 10] - [4, 13]
        (type [4, 10] - [4, 13]))))
  (function [5, 0] - [5, 11]
    name: (variable [5, 0] - [5, 1])
    patterns: (patterns [5, 2] - [5, 7]
      (pat_record [5, 2] - [5, 7]
        fields: (pat_fields [5, 2] - [5, 7]
          (pat_field [5, 4] - [5, 5]
            (field_name [5, 4] - [5, 5])))))
    rhs: (exp_name [5, 10] - [5, 11]
      (variable [5, 10] - [5, 11])))
  (signature [7, 0] - [7, 8]
    name: (variable [7, 0] - [7, 1])
    type: (type_name [7, 5] - [7, 8]
      (type [7, 5] - [7, 8])))
  (function [8, 0] - [8, 14]
    name: (variable [8, 0] - [8, 1])
    rhs: (record_update [8, 4] - [8, 14]
      (variable [8, 4] - [8, 5])
      (ERROR [8, 8] - [8, 12]
        (variable [8, 8] - [8, 9])))))
```

**Comment by Maskhjarna** [comment]
Wildcards don't appear to be valid expressions by themselves when pattern matching, like

```purescript
module Test where

not :: Boolean -> Boolean
not =
  case _ of
    true -> false
    false -> true
```

gives

```
(purescript [0, 0] - [7, 0]
  name: (qualified_module [0, 7] - [0, 11]
    (module [0, 7] - [0, 11]))
  (where [0, 12] - [0, 17])
  (ERROR [2, 0] - [6, 17]
    (pat_typed [2, 0] - [3, 3]
      pattern: (pat_name [2, 0] - [2, 3]
        (variable [2, 0] - [2, 3]))
      type: (fun [2, 7] - [3, 3]
        (type_name [2, 7] - [2, 14]
          (type [2, 7] - [2, 14]))
        (type_apply [2, 18] - [3, 3]
          (type_name [2, 18] - [2, 25]
            (type [2, 18] - [2, 25]))
          (type_name [3, 0] - [3, 3]
            (type_variable [3, 0] - [3, 3])))))
    (wildcard [4, 7] - [4, 8])))
```

Maybe [this doc on pattern matching](https://github.com/purescript/documentation/blob/master/language/Pattern-Matching.md) could be helpful. I'd look more into it if I had more time at hand.

**Comment by postsolar** [comment]
That's right, I saved those for the next PR to keep this one more or less focused on the records + small things. Adding them to `if _ then _ else _` and `case _ of` is easy, but wrt operator sections
```(_ `arbitrary expression which isn't a thing in haskell` 1)``` it's hard and I suspect will get even harder, so I'm not including them yet.

**Pull request merged**
